%YAML 1.1
# ^-- ATTN: [2019-12-31] If you use a later version, Github will fail
#     with a bogus error message "You have an error in your yaml syntax".
# -*- coding: UTF-8, tab-width: 2 -*-
---

on:
  push:
    branches:
      - '*'

jobs:
  job_npm_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - '8.x'
          - '12.x'
          - '16.x'
          - '20.x'

    steps:
      - uses: actions/checkout@v4
      - uses: mk-pmb/github-ci-util-2405-pmb/act/install@experimental
        with:
          nodejs_version: ${{ matrix.node-version }}

      - run: ghciu npm install .
      - run: >
          ln --symbolic --no-target-directory -- ..
          node_modules/equal-pmb || true
      - run: ghciu npm test


...
